### ISSUE TITLE
Datetime picker not working with aot

### ISSUE THREAD

**Issue by Gost99** [h2qutc/ngx-mat-datetime-picker#24]
**Code (from example):**
```
<mat-form-field>
    <input matInput [ngxMatDatetimePicker]="picker" placeholder="Choose a date" [formControl]="dateControl">
    <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
    <ngx-mat-datetime-picker #picker></ngx-mat-datetime-picker>
</mat-form-field>
```

**Error:**
Type 'NgxMatDatetimePicker<any>' is not assignable to type 'MatDatepicker<any>'.

**Comment by h2qutc** [comment]
Hi, 
This repo is no longer supported, please consider using the repository [angular-material-components](https://github.com/h2qutc/angular-material-components) instead.

This issue was fixed in [@angular-material-components/datetime-picker](@angular-material-components/datetime-picker) v2.0.1

```
npm install --save  @angular-material-components/datetime-picker
```
Free free to open issue [here](https://github.com/h2qutc/angular-material-components/issues).
Thank you very much.
