### ISSUE TITLE
Ability to add some validation pattern to the time inputs

### ISSUE THREAD

**Issue by milosmih** [h2qutc/ngx-mat-datetime-picker#37]
1)  Currently into the time input we can type any text, on submit input is cleared and value is 00;
2)  Also we can type large numbers (example 10000), for hours, minutes and seconds. After submit value is unpredictable. Sometime it is error, sometime some huge date depends on how big number is.

Is there any way that we can prevent user to enter wrong values. 
For instance:
  - User can type only numbers from 00 - 23, for hours
  - User can type only numbers from 00 - 59, for minutes
  - User can type only numbers from 00 - 59, for seconds

**Comment by h2qutc** [comment]
Hi, this bug was fixed in version v2.0.2.
User cans type **only the numbers** and auto-corrected in range 00-23 for hours, 00-59 for minutes/seconds.
For example:
If user type 65 for input Hour, the value is auto-corrected into 17. (65 % 24 = 17)
If user type 65 for input Minute, the value is auto-corrected into 5 for example.
Thanks !!!

**Comment by milosmih** [comment]
Thanks :)
